### ISSUE TITLE
Add RegionYolo

### ISSUE THREAD

**Issue by tzerrell** [plaidml/openvino#38]
Add support for the RegionYolo op to the PlaidML plugin. It is possible that code for this already exists and just needs to be wrapped in calling code in `inference-engine/src/plaidml_plugin/ops/region_yolo.cpp`.

**Comment by tzerrell** [comment]
@mwyi is not going to be able to work on RegionYolo in the near term and this is one of the higher priority ops that's still outstanding. @YangleiZouIntel would someone on your team be available to work on this soon?

**Comment by YangleiZouIntel** [comment]
Implemented in https://github.com/plaidml/plaidml/pull/1646
