### ISSUE TITLE
Add Bucketize

### ISSUE THREAD

**Issue by tzerrell** [plaidml/openvino#48]
This might be more efficient if we can directly write SCF dialect (https://github.com/plaidml/plaidml/issues/1494).

However, I believe this is nonetheless currently possible: repeat to add a new dimension whose size is the number of bucket divisions, broadcast-compare to each bucket value in this axis, do a sum contraction/reduction over this axis to get the bucket number.

**Comment by XinWangIntel** [comment]
Add https://github.com/plaidml/openvino/pull/90  to implement the broadcast version. It seems the dialect way can let us define  a specific algorithm but not follow the style of most ops.
