### ISSUE TITLE
Add SoftPlus

### ISSUE THREAD

**Issue by tzerrell** [plaidml/openvino#84]
Consider if it should be an eDSL intrinsic (https://github.com/plaidml/plaidml/issues/1496)

**Comment by mwyi** [comment]
Eltwise version for now (https://github.com/plaidml/plaidml/pull/1567)

**Comment by tzerrell** [comment]
Done for now, possible followup (a softplus intrinsic) is tracked in https://github.com/plaidml/plaidml/issues/1496
